export default {
  FETCH_START: "FETCH_START",
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_MOVIE_SUCCESS: "GET_MOVIE_SUCCESS",
  POST_MOVIE_SUCCESS: "POST_MOVIE_SUCCESS",
  POST_MOVIES_SUCCESS: "POST_MOVIES_SUCCESS",
  FETCH_ERROR: "FETCH_ERROR",
  DELETE_MOVIE_SUCCESS: "DELETE_MOVIE_SUCCESS",
  CLEAR_ERROR: "CLEAR_ERROR",
  CLEAR_ACTIVE_MOVIE: "CLEAR_ACTIVE_MOVIE",
  SET_SEARCH: "SET_SEARCH",
  SET_SEARCH_FILTER: "SET_SEARCH_FILTER",
};
