export default {
  FETCH_START: "FETCH_START",
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_MOVIE_SUCCESS: "GET_MOVIE_SUCCESS",
  POST_MOVIE_SUCCESS: "POST_MOVIE_SUCCESS",
  FETCH_ERROR: "FETCH_ERROR",
  DELETE_MOVIE_SUCCESS: "DELETE_MOVIE_SUCCESS",
};
